### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by NayanKaran** [NayanKaran/space-travelers-hub#25]
Hi,

The link to the GitHub project is given below,

https://github.com/NayanKaran/space-travelers-hub/projects/1

Kindly note that we are two person group.

**Comment by zhadier** [comment]
## Hi @NayanKaran & @abdulhamiid  👋  

Your kanban is complete!  There is nothing else to say other than... it's time to rock and roll :shipit: 

# Congratulations! 🎉 

### Keep Rocking!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
